@baseUrl = http://localhost:3001

### Trae todas las categorias 
GET {{baseUrl}}/categorias

### Trae todos los productos de una categoria
GET {{baseUrl}}/productos/2

### Prueba de traer una categoria que no existe
GET {{baseUrl}}/productos/4

### Trae un producto por id
GET {{baseUrl}}/producto/1

### Prueba de traer un producto que no existe
GET {{baseUrl}}/producto/200

### Crea una nueva compra 
POST {{baseUrl}}/compra

### Trae una compra por id
GET {{baseUrl}}/compra/1

### Agregar un producto a la compra
POST {{baseUrl}}/compra/1/2/Memoria:128GB

### Quitar un producto de la compra
DELETE {{baseUrl}}/compra/1/2/Memoria:128GB

### Confirmar la compra
PUT {{baseUrl}}/compra/1/confirmar

### Cancelar la compra
DELETE {{baseUrl}}/compra/1/cancelar

### Actualizar datos del cliente en una compra
POST {{baseUrl}}/compra/2/cliente
Content-Type: application/json

{
    "domicilio": "Calle Falsa 123",
    "localidad": "Springfield",
    "codigoPostal": "12345",
    "email": "cliente@example.com",
    "telefono": "1234567890",
    "tarjeta": "4111111111111111"
}

### Intentar actualizar cliente en una compra que no existe
POST {{baseUrl}}/compra/999/cliente
Content-Type: application/json

{
    "domicilio": "Calle Falsa 123",
    "localidad": "Springfield",
    "codigoPostal": "12345",
    "email": "cliente@example.com",
    "telefono": "1234567890",
    "tarjeta": "4111111111111111"
}
